---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-creds
  namespace: keycloak
spec:
  encryptedData:
    password: AgBRsfUmOnyFfYt+PMxNAVNMLgOOLDWtI28uVNGgjELm/yVwHRMOtoYvOc5FksH09X8ZDcHhS0Qw6SWit2SEbB1DFtYUjDT0dZcjXCc4pMw2j+id29FkfHWQQMTtBRmoS0CfECMAZJ7zafJkRyvzqSmGjfbeVOK+94xKarGeVzISVQvb02ZQLIM/aYdClLc8W5K6vyzHkdqayunQt4D4A2p9KCLhId+Gn3ey7Wr1UQjUkpykYPw6edXdf5RhDSMjsdC8v0X2W5GMd61UufFLZ82VjnMxSTmmcMb4dMPktZEmriJ0VFmiiaKQgWgWjbZCvjGeUsUloofwCNaNHnyWq5l/uO/kPOWbZYHwEJbQwEz5bCMD4xNfH5qH/mKjTtDqZ/19FV8PjOcH7c7sILBokxRF29iwk5kb9DG/vOMfzaIQWYazu2LSzDrDMr+/acLzX0ecV608BAIviR7ekPYSaVH1/5jIq9EONgLEcWpg+qtyjNcNraLGXlzZSfwrrPoTvHrflzoGcXlrDI2yoZzegU112NIPNNvG5OspL9nFgB4cKzma2Ge5Muq2IxXlKX5Qn0fTUH90t4tTmHjXMGUPRAR7D4AJi16tAWA/E2tcTHMimGKOSsbg0hHNRtYg4ypMi8KB7D3VeQ1SriJH6CZrohlS/0ZHxTQM3cYSb3jLnQf+ysxt9C8szu96YryENeD2RNYE36EfoeAmgY3GiA==
    username: AgBEY936NexN6GjEocdfRtkg8oa/CWHSHLtHy4GlDyn704N55DYpT3iIOhkpkaIBkaZlqZQGnuyX6F5BHIkcw4jtsyLmd1O8v7DrADdXPdfz/+DXeLCphbKth881ettSM7EoMS1OLERa/+8qNZ4CjE+zPdKt0jlEF3WEVfsuJ1LVYA/GIhOQ/nl1GxuYl83TKa01ChP08U+Q6qsOEiJHERQvmyVJwHaKJpyimWvRC1kzSiJOhim38GZts5M/nivDTxPAI6XHDGxX70rGo3ZawklORnOrASbCc0welS2GHv3a/a9o3aNm31YAe87dajDmWJs2WtEg7obxNCLuLk+5ELDgy2vsRAjRomJsGLgZ3NiG6wm6/qgAUZvj/vY3H37ogaZx7KqW2FqAaYkKlGwUzWCUv97D7PGNtMZvLyg0bVXgIsJJXuk3hQhffj0vT1wALm88+mwN3p//WXrQmWt/v7UWyvnleSNOsXhWtGFKCPkQiidolrtcwPhL0fpg8ieUiwQwreIiVO1g+0+IcBlCeRyn6rjZdygdlrWzWTiPhfL0zeMEJ5hePKstf7hwtBK90Yue4zCK85gK0a5aY6X6rKK+yGX1Mu2Aip+Th9qWQ94Sta+pXYEBMmI4rhutfZQh2OM9skgTbDcg3yBrBlG404WT2o1IotzvsDllsKP72OjqX5Ux16VqdMym2P2scNDCcvmZ00ypAA==
  template:
    metadata:
      name: keycloak-creds
      namespace: keycloak
