apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: daily-cleanup
  namespace: argo
spec:
  schedule: "0 0 * * *" # 0 Uhr
  concurrencyPolicy: Replace
  startingDeadlineSeconds: 0
  workflowSpec:
    serviceAccountName: cleanup-sa 
    entrypoint: cleanup-pods
    templates:
      - name: cleanup-pods
        container:
          image: bitnami/kubectl:latest
          command: ["/bin/sh", "-c"]
          # Vor 24h werden pods die nicht benutzt werden automatisch gelöscht.
          args:
            - |
              
              TARGET_TIME=$(date -d '24 hours ago' +%s)
              
              
              kubectl get wf -l "workflows.argoproj.io/completed=true" -o jsonpath='{range .items[*]}{.metadata.name}{"\t"}{.metadata.creationTimestamp}{"\n"}{end}' | \
              while read name time; do
                
                wf_time=$(date -d "$time" +%s)
                
                
                if [ "$wf_time" -lt "$TARGET_TIME" ]; then
                  echo "Deleting old workflow: $name"
                  kubectl delete wf "$name"
                fi
              done