
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Auflistung aller Kubernetes-Manifeste in diesem Verzeichnis
resources:
  - system-health-check.yaml
  - trivy-security-audit.yaml
  - user-security-audit.yaml
  - cleanup-cron.yaml