apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: falcosidekick-monitor
  namespace: falco
  labels:
    release: prometheus-stack 
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: falcosidekick 
  endpoints:
    - port: metrics 
      interval: 30s