---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-creds
  namespace: argo
spec:
  encryptedData:
    password: AgAn3+VT5sQBb5IQQpGZn+TWiIgMSLw8cj2rrJsIcVRnEkD/m27J0bWbt3beAupCJ9YJLVidxaYAPmtQwfw5PKrqnyZQwbZt+trp/msOZffb1bvV1ufTJ8uNs3EgoNVPrTXz2HfExNM1wB2G001IlqmTt6p/bA5LVMngVaeyQc5ZABOm7n1pGXfMovi7nH2MgzYOEwwH+9vfuRaNw4NLQBkp98d1eL3Fcu2hLK+gDomFjs6aEiGJisa0WgzT36/1hwjKhwHti6O4Ja+GHaUZs/ikrA9eOIiTu6m9Fg+I5KOLu/+WhJU8hCAI0jOlVesd/FfbPnNRqJoZ7wrYS/qH7RfPThelF84J34LhliNg/qyJvt9RaBHaDYqXDGVyG2qauUoJmkyFBdFM3tMz+5xmys0xwvqDXYzkvHaxdxWum1BSy03eeHY5LBGL6sF0pJaVxvFCodRwQWDgedugunezBuahwz7zAZuWUn6dwKJTlg0A78J2MCZKlWSbMWyunZm/C1c5tMj551p3C7aNQ+wcVAo71cB8uIhsUW6E/JfvKipqvhWCmwzAFLcPFn5gRAu8YXR+wTuym8Xy8hVP8DK+PNKCt/uMcq1a7rY7F9tIjLG2sbljCB7bRLiBxFio4itBhwKOqQNqVbUzLKYePQa2ITu1q1a3Md5YiCO6dSuqdo4hkwL0AFqqkA8HotMlWSfy7RqyXahcQlj/OBSMiQ==
    username: AgBtbP2fGeI15sJpJOtQ4IvBpEKmU3y2glbfRZ9EEIJNcd2Vp/PPLuUgkNpgYj6jAKCxUIP2g8VuDEHFXq6z12vbuNZbC80NQ0fkOwdAQe6l5iSyZZga9dJklqsO7ZFX3CxYYtfgFkcYAX47XIuqD97MSBhQ8hAm0HO/59QO+Ogct610Q2eHz+bHvN5M0/jwsMrRRUHzKeWAeBMUyeGudhyS3opLIUBJgMPQ4ohrkcyN9Enjf/od5xwkN2qUsXVn98K+w9UISfd/SLKXzzHcdTK7g+nf6r0us/HIWmNeSiNMH+o+eptpY3Ob+KVk4GyL4RxEGh0kU+xudmL0NlsRiFF0YjbBeg7q0xLTGpqLz0DcNK0ibmQd6eRGaB8oB0u29ftCwm0ZXNu0GG5yFRmW8rGlprGTgNOgclju3JMGH+eYOjZCjooofcBObupWTT6jw0K4h3X/VYiAdI6mqqHFMgWLvV6s1DmogE5/yI0V0SIEBqgnboXUVbFhwBpd4YqZNyns07GrmSSwZw2Uh6olOTM2FSJySDBRZYUg8R0hTP7smsS82dD2Y2T1GsRPIZdLrIA2duKIoSQEYdtisg/6NO+YKT6XMqIShAxDpjmBbZZJS4ygaoOfK7SgYB7gD/VX3fyNzEdku7YmIqcbfb65NiLuNCI9WcyjH0wkwtXMsh9fMhbTNsFViWGeJHzW2CzmN8KdiUdqUw==
  template:
    metadata:
      name: keycloak-creds
      namespace: argo
