apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: falco
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://falcosecurity.github.io/charts
    chart: falco
    targetRevision: 4.0.0
    helm:
      values: |
        # -- Treiber-Konfiguration: Verwendung von Modern eBPF für maximale Kompatibilität
        driver:
          enabled: false      # Deaktiviert den alten Driver-Loader
          kind: modern_ebpf    # Nutzt BTF-Technologie, kein Build auf dem Host erforderlich

        # -- Falcoctl: Automatisierung von Rules und Artifacts
        falcoctl:
          artifact:
            install:
              enabled: true   # Installiert Standard-Regelsätze beim Start
            follow:
              enabled: true    # Überwacht Aktualisierungen der Regeln

        # -- Hauptkonfiguration von Falco
        falco:
          privileged: true    # Erforderlich für den Zugriff auf Kernel-Schnittstellen
          
          # Ausgabe-Einstellungen (JSON für SIEM/Sidekick-Integration)
          json_output: true
          stdout_output:
            enabled: true
          
          # Weiterleitung der Alarme an Falcosidekick
          http_output:
            enabled: true
            url: "http://falco-falcosidekick:2801/"

        # -- Falcosidekick: Visualisierung und Benachrichtigung
        falcosidekick:
          enabled: true
          webui:
            enabled: true     # Aktiviert das Web-Dashboard für Echtzeit-Monitoring
  destination:
    server: https://kubernetes.default.svc
    namespace: falco
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true