apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: falco
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://falcosecurity.github.io/charts
    chart: falco
    targetRevision: 4.0.0  
    helm:
      values: |
        driver:
          enabled: true
          kind: modern-ebpf
        mounts:
          hostRoot: true
        driverLoader:
          enabled: false
      falco:
        privileged: true
        tty: true
        http_output:
          enabled: true
          url: "http://falcofalcosidekick:2801/"
      falcosidekick:
        enabled: true
        metrics:
          enabled: true
        webui:
          enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: falco
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true