apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: keycloak-audit-templates
spec:
  entrypoint: user-scan
  templates:
  - name: user-scan
    inputs:
      parameters:
      - name: keycloak-url
        value: "http://keycloak.keycloak.svc.cluster.local:80" 
      - name: realm
        value: "master"
    script:
      image: python:3.9-slim
      command: [python]
      env:
      - name: ADMIN_USER
        valueFrom:
          secretKeyRef:
            name: keycloak-creds
            key: username
      - name: ADMIN_PASS
        valueFrom:
          secretKeyRef:
            name: keycloak-creds
            key: password
      source: |
        import subprocess
        import sys
        import os

        # python-keycloak installieren
        subprocess.check_call([sys.executable, "-m", "pip", "install", "python-keycloak", "-q"])

        from keycloak import KeycloakAdmin

        try:
            print("--- Audit Start ---")
            admin = KeycloakAdmin(
                server_url="{{inputs.parameters.keycloak-url}}",
                username=os.getenv("ADMIN_USER"),
                password=os.getenv("ADMIN_PASS"),
                realm_name="{{inputs.parameters.realm}}",
                verify=False
            )

            users = admin.get_users({})
            print(f"--- Audit Report Start ---")
            
            unsafe_users = []
            for user in users:
                
                user_detail = admin.get_user(user['id'])
                
                creds_types = user_detail.get('disableableCredentialTypes', [])
                has_mfa = any('otp' in t.lower() or 'webauthn' in t.lower() for t in creds_types)
                
                status = " MFA Enabled" if has_mfa else " MFA Not Configured"
                print(f"User: {user['username']} - {status}")
                
                if not has_mfa:
                    unsafe_users.append(user['username'])

            if unsafe_users:
                print(f"\n Warning: The following users have weak security settings: {', '.join(unsafe_users)}")
            else:
                print("\n All users have good security settings.")

        except Exception as e:
            print(f"Error occurred: {e}")