apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: keycloak-templates
spec:
  templates:
  - name: audit-users
    script:
      image: python:3.9-slim
      command: [python]
      source: |
        # hier könnte der Code für die Benutzerüberprüfung in Keycloak stehen
        print("Benutzer-Sicherheitsüberprüfung wird durchgeführt...")