apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fluent-bit
  namespace: argocd
spec:
  project: default
  source:
    chart: fluent-bit
    repoURL: https://fluent.github.io/helm-charts 
    targetRevision: 0.57.1 
    helm:
    
      values: |
        config:
          inputs: |
            [INPUT]
                Name           tail
                Path           /var/log/containers/*.log
                Exclude_Path   /var/log/containers/fluent-bit*.log
                Tag            kube.*
                Mem_Buf_Limit  5MB
          outputs: |
            [OUTPUT]
                Name           loki
                Match          *
                # monitoring namespace loki senden
                Host           loki.monitoring.svc.cluster.local
                Port           3100
                Labels         job=fluent-bit
                Auto_Kubernetes_Labels on
  destination:
    server: https://kubernetes.default.svc
    namespace: logging # Logging namespace deployment
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true # wenn Namespace nicht existiert, wird er erstellt