apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-workflows-collection 
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Ikayou/my-devsecops-platform.git
    targetRevision: HEAD
    path: workflows/base/templates  
  destination:
    server: https://kubernetes.default.svc
    namespace: argo  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true