apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-stack 
  namespace: argocd
spec:
  project: default
  source:
    chart: kube-prometheus-stack
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 61.3.3
    helm:
      values: |
        grafana:
          service:
            type: NodePort

          envValueFrom:
            GF_SMTP_PASSWORD:
              secretKeyRef:
                name: grafana-smtp
                key: GF_SMTP_PASSWORD

          grafana.ini:
            smtp:
              enabled: true
              host: smtp.gmail.com:587
              user: ikari.com56@gmail.com
              password: $__env{GF_SMTP_PASSWORD}
              from_address: ikari.com56@gmail.com
              from_name: Grafana
              skip_verify: true
              
  destination:
    server: "https://kubernetes.default.svc"
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    
    syncOptions:
      - CreateNamespace=true  
      - ServerSideApply=true