apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-stack
  namespace: argocd
spec:
  project: default
  source:
    chart: kube-prometheus-stack
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 61.3.3
    helm:
      values: |
        grafana:
          service:
            type: NodePort
          
          env:
            GF_SMTP_ENABLED: "true"
            GF_SMTP_HOST: "smtp.gmail.com:587"
            GF_SMTP_USER: "example@gmail.com"
            GF_SMTP_FROM_ADDRESS: "example@gmail.com"
            GF_SMTP_FROM_NAME: "Grafana"
            GF_SMTP_SKIP_VERIFY: "true"

          envValueFrom:
            GF_SMTP_PASSWORD:
              secretKeyRef:
                name: grafana-smtp
                key: GF_SMTP_PASSWORD

          sidecar:
            datasources:
              enabled: true
              defaultDatasourceEnabled: false

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    #automated:
      #prune: true
      #selfHeal: true
    syncOptions:
      - CreateNamespace=true
      #- ServerSideApply=true