---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: slack-api
  namespace: argo
spec:
  encryptedData:
    webhook-url: AgAcW9uJk0mOxUfjGO7zMSlejinOY2BC0VAEYYY1uRdjDcB/4NUxycZdMqcze8KoLQCUN1Vgwr4FnoNYxnQtJo+tdzd5BoRzY7SazPcxwhu4RvJQmq0K8fZL0gFDI3Z44wLKaEPZ9eBI7+xnBA8kBhowprkDJ93btPUouJBXPP+pQmUoJ7OVTbBbGUqjApYgfaPal61rEVv74zuFIryUmosJuvFAdf0MFeYDUVyTgohgvtJPbjHStDPKPXqodcCVWAI3FV1E7rZmUHL3Qx9wbuhAfCzzIMpzDvTVuj6VgwfMJZbckJ1iArZpQ6HWxt6l0/NRx2pUiT5a2IyWpr58THODRGVzYDEiaGs2IEmqWTHZt5HilvL8h+QxhmLem3u1Aq918yxQnQ86CCZKsjiGbFjoz9/NFG3o30xwSDaKmHsz6+NnimEPpk3cVNtvkiQ4FFRotTITLA4rTzb3mXytAOyX6uk0xKSU1xKCZ5w879tBRxBMBlmoEr1KNOSM61zZU1A3n80UaMl77Itk8EaNi6k4hFp8hpPZJ82jXOFx5kT/dIrSbVywOPMzKVtW31nXky4LEy4/ggvK9E1U9d6gNAgDnONYQswJjvBi72JfzOKWEL0q+11z/3y29TpbImD4w12l1lgMXbKWRL5+ILa1GgH7aiLsC24i1hpvwUPQIM736ZK13e7aAJiJSofmhaNYENEORfRsPZ6CjS8BeACshcqjzjIfSRFhBxjNi0yAKkG9bgsVhDPCKrCgMLz0vsPr1FJNlYYG2jWSabpvb4r9CkX1USyy4u8aRMBH/8fJscgUoCQ=
  template:
    metadata:
      name: slack-api
      namespace: argo
