---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: slack-api
  namespace: argo
spec:
  encryptedData:
    webhook-url: AgAI/JlA9wLf/b6x3yp0gejHNBqBWBufcR/4ZV96Us3F3Iji9DxFogIAfp0+iHfYQD4kwP05MfPg3jnawv5sBk+HCyLH8Xk7M0RcYXoQRceb7FcoQivxpEQK8QqJofXwR4zKq1AA3foalvqLdLBmub3AGDLYe2rkPgJvk5yJMKC5arkJ2X0UWuyQK5b1dwT5YBQi+xn6KPG2euX+jVx8iiUCzApdv3xRDvOhnFgfQ1AYvLRtfBCh1KO89tftpU/XZnh1bj8GAVqFXSV7nZ8HprqtgNlfy4LZ6FtNN8hZWsTuhqrvOpjqeV50u8ufUGz3Sb5cTLzimrYGkx1tCogDtzf5fiJU3cRFkSMt0fG/yqjhOi+1FZjppzi4EyyPTXmkSPPh/SEw/9oMdN58V1WI/a9kRjc8TidPi+/idXhFKl4Qu7Q7+c4EJPul+ywB5iP/yFITofaLI9kO/Rq7nl0PPWDgCojtzWI3V6Yjj5ZzyOjLQDnTjqesGhlL7k+Ho+fbiiNDVPtWAskrB9Giz3Yfb/73IbVHB/wAc7Oc2fkijKk1qrX81nRTTSvbaeOnyQrN1ReKNAir5WwmmF+WxTc7xnP8HKbTXAIWT/fpFO8xNyh8NUqY9ARyz+C//u86cp53OcZGRWhMvipqxhaHokY6+qrwfPOFZop1WP4c7d1sL5CI431MUV6CDOTqpogSswx9sfHv1a7/hw31l3FeaZ0JX8bdYX4ehBn0HVfMhT4di78K0EE0DoQQgSx/h3gynG1xPDvXFMIaLHmWgUzuJvaNYjPmi+r/NFA83eQmWAsnC3jz3Jp2nrr1t3z3UqrF6XgKyfKiSyOOnQDnBH/I7HflE1v5QTY=
  template:
    metadata:
      name: slack-api
      namespace: argo
