name: Security Scan
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  scan:
    name: Trivy Vulnerability Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          # scan image
          image-ref: 'quay.io/keycloak/keycloak:24.0.0'
          format: 'table'
          exit-code: '1' # wenn Schwachstelle gefunden wird stoppt es.
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'