name: Security Scan
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: 'true'
jobs:
  scan:
    name: Trivy Vulnerability Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          # scan image
          image-ref: 'quay.io/keycloak/keycloak:latest'
          format: 'table'
          exit-code: '0' # wenn Schwachstelle gefunden wird stoppt es.
          ignore-unfixed: true
          severity: 'CRITICAL'